spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cosmetics?serverTimezone=Asia/Seoul
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
hibernate:
  globally_quoted_identifiers: true
