security:
  oauth2:
    client:
      registration:
        google:
          client-id: 327040840076-kves9pbre6olt2rg6pqbv5af85oj9bkq.apps.googleusercontent.com
          client-secret: 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
          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - profile
            - email
        facebook:
          client-id: 5559382764078339
          client-secret: dfefaa8250c6906317f285279ac39193
          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
        kakao:
          authorization-grant-type: authorization_code
          client-id: d7e90599a097fde02926aadac1e79fca
          client-secret: sGqdBHEsA1txaHrqLDdcFSdVUSkVTAMU
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope:
            - profile
            - account_email
          client-authentication-method: POST
          client-name: Kakao
        naver:
          authorization-grant-type: authorization_code
          client-id: k2M0jVpTmaj2IpGIfdhB
          client-secret: ZHEcsUh2FG
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope: name,email,profile_image
          client-name: Naver

      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: properties
          # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
          # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.