spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          facebook:
            client-id: 986489005584342
            client-secret: 72a00e67e3115f928cfc70004ba671cc
            scope: email
          google:
            client-id: 327040840076-kves9pbre6olt2rg6pqbv5af85oj9bkq.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          kakao:
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-id: d7e90599a097fde02926aadac1e79fca
            client-name: kakao
            client-secret: sGqdBHEsA1txaHrqLDdcFSdVUSkVTAMU
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname,profile_image,account_email
          naver: ''
          naver.authorization-grant-type: authorization_code
