spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 327040840076-kves9pbre6olt2rg6pqbv5af85oj9bkq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          facebook:
            client-id: 554879852594717
            client-secret: 82fb025c0dfa998ae02d459ace18483f
            redirect-uri: "http://localhost:8080/login/oauth2/code/facebook"
            scope:
              - email
              - public_profile

          kakao:
            authorization-grant-type: authorization_code
            client-id: b3d3d14f470136f6484cfe006016559a
            client-secret: efIEYKdwDexMAWsVvtEJGQBTsZQ23qLE
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST


          naver:
            authorization-grant-type: authorization_code
            client-id: k2M0jVpTmaj2IpGIfdhB
            client-secret: ZHEcsUh2FG
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - nickname
              - email
              - profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id
