
logging:
  level:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cosmetics?serverTimezone=Asia/Seoul
    username: root
    password: A520602bc@
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
  main:
    allow-circular-references: true
  profiles:
    include: oauth
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
